### PR TITLE
Fix issue #73 "Unity Hub: Bad CPU type in executable"

### LINKED ISSUE #73: macOS runners are now failing with "Unity Hub: Bad CPU type in executable"
After changes in #72 some macOS related jobs are now failing with this:

```
font-mansalva                            vcam
font-manuale                             warcraft-logs-uploader
font-maple                               wins

You have 4 outdated formulae installed.

==> Downloading https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.dmg
######################################################################### 100.0%
Warning: No checksum defined for cask 'unity-hub', skipping verification.
==> Installing Cask unity-hub
==> Moving App 'Unity Hub.app' to '/Applications/Unity Hub.app'
🍺  unity-hub was successfully installed!
Unity Hub installed successfully.
npm WARN exec The following package was not found and will be installed: unity-changeset@2.1.2
++ '/Applications/Unity Hub.app/Contents/MacOS/Unity Hub' -- --headless install --version 2022.3.33f1 --changeset b2c853adf198 --module mac-il2cpp --childModules
/bin/bash: line 65: /Applications/Unity Hub.app/Contents/MacOS/Unity Hub: Bad CPU type in executable
++ set +x
Could not install the Unity Editor.
Please try again or open an issue.
Something went wrong.
Please try again or open an issue.

Exited with code exit status 1
```

Any help would be appreciated :)

### PR DESCRIPTION
**Pull request by HashbangGames**
#### Changes
- Updated enums to reflect depricated environments, the only supported environments for macos are non-intel based M1's.
- Fixed Bad CPU issue by using rosetta2 to run unity hub.

#### Checklist

- [x] Read the contribution [guide](/game-ci/unity-orb/blob/main/CONTRIBUTING.md) and accept the [code](/game-ci/unity-orb/blob/main/CODE_OF_CONDUCT.md) of conduct
- [x] Documentation (updated or not needed)
- [x] Tests (added, updated or not needed)

Closes #73

### CODE REVIEW

File: src/scripts/macos/prepare-env.sh [hunk 1]
```diff
@@ -8,6 +8,21 @@ readonly unity_editor_path="/Applications/Unity/Hub/Editor/$UNITY_EDITOR_VERSION
...
+      echo "Rosetta 2 installed successfully."
+    else
+      echo "Failed to install Rosetta 2."
+      exit 1
+    fi
+  else
+    echo "Rosetta 2 is already installed."
+  fi
+}
+
```
Comment (GabLeRoux) [inline src/scripts/macos/prepare-env.sh:25]: We should keep an eye on updates from Unity for native ARM64 support, but I think this is the correct fix for this :+1: nice work 🙌

File: src/scripts/macos/prepare-env.sh [hunk 2]
```diff
@@ -44,7 +59,7 @@ check_and_install_unity_editor() {
       changeset="$(npx unity-changeset "$UNITY_EDITOR_VERSION")"
 
       set -x
-      "$unity_hub_path" -- --headless install --version "$UNITY_EDITOR_VERSION" --changeset "$changeset" --module mac-il2cpp --childModules
+      arch -x86_64 "$unity_hub_path" -- --headless install --version "$UNITY_EDITOR_VERSION" --changeset "$changeset" --module mac-il2cpp --childModules  -a arm64
```
Comment (GabLeRoux) [inline src/scripts/macos/prepare-env.sh]:
```suggestion
      arch -x86_64 "$unity_hub_path" -- --headless install --version "$UNITY_EDITOR_VERSION" --changeset "$changeset" --module mac-il2cpp --childModules -a arm64
```

I would remove the extra space here.

**Review by GabLeRoux — APPROVED** [review]
